/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import classes.Question;
import classes.getQuestions;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import static java.awt.Component.BOTTOM_ALIGNMENT;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.Reader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;

/**
 *
 * @author Green
 */
public class MainWindow extends javax.swing.JFrame {

    private static int i = -1;

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 956, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    static List<Question> preguntas;
    public static final Dimension ss = Toolkit.getDefaultToolkit().getScreenSize();

    public static void main(String args[]) throws FileNotFoundException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                //preguntas = getQuestions.readLines();
                loadData();
                
                runComponents(true);
            }
        }
        );

    }

    public static void loadData() {
        try {
            //  Carga de preguntas y respuestas
            //preguntas = getQuestions.readLines();

            String jstring = "";

            Gson gson = new GsonBuilder().create();

            String fileName = "\\output.json";
            Path path = new File(new File("").getAbsolutePath() + fileName).toPath();

            try (Reader reader = Files.newBufferedReader(path)) {

                Question[] quests = gson.fromJson(reader, Question[].class);

                preguntas = Arrays.asList(quests);
            }

        } catch (Exception e) {
            System.out.println("Error JSON");
        }
    }

    public static void runComponents(boolean sum) {

        //  Lógica para iterar @preguntas
        if (sum) {
            if (i != 1004) {
                if (preguntas.get(++i).isAnswered()) {
                    runComponents(sum);
                }
            } else {
                i = 0;
            }

        } else {
            if (i != 0) {
                if (preguntas.get(--i).isAnswered()) {
                    runComponents(sum);
                }
            } else {
                i = 1004;
            }
        }

        //  Declaración de elementos de la interfaz
        JFrame mw = new MainWindow();
        JLabel enunciadoLabel = new javax.swing.JLabel();
        JPanel panelPrincipal = new JPanel();
        JPanel panelRespuestas = new JPanel();
        JPanel panelBotones = new JPanel();
        JButton botonNext = new JButton();
        JButton botonSend = new JButton();
        JButton botonPrev = new JButton();

        //  Ventana principal
        mw.setVisible(true);
        mw.setExtendedState(JFrame.MAXIMIZED_BOTH);

        //  Panel que va a contener el resto de elementos
        panelPrincipal.setLayout(new BoxLayout(panelPrincipal, BoxLayout.Y_AXIS));
        panelPrincipal.setSize(ss);
        panelPrincipal.setVisible(true);
        mw.add(panelPrincipal);

        //  Enunciado
        enunciadoLabel.setVisible(true);
        enunciadoLabel.setText(convertToMultiline(i
                + "Chapter: "
                + preguntas.get(i).getChapter()
                + " Question: "
                + preguntas.get(i).getNumber()
                + "\n"
                + preguntas.get(i).getQuestion()));
        panelPrincipal.add(enunciadoLabel);

        //  Panel contenedor de los RadioButtons de las respuestas
        panelRespuestas.setVisible(true);
        panelRespuestas.setLayout(new BoxLayout(panelRespuestas, BoxLayout.Y_AXIS));
        panelPrincipal.add(panelRespuestas);

        //  Función que crea los RadioButtons dependiendo del numero de respuestas
        setRadioButtons(i, panelRespuestas);

        //  Panel para los botones de control (prev,send,next)
        panelBotones.setLayout(new BoxLayout(panelBotones, BoxLayout.X_AXIS));
        panelBotones.setVisible(true);
        panelPrincipal.setSize(ss);
        panelPrincipal.add(panelBotones);

        botonPrev.setText("<--");
        botonPrev.setVisible(true);
        botonPrev.addActionListener((ActionEvent e) -> {
            //your actions
            mw.dispose();
            runComponents(false);
        });
        panelBotones.add(botonPrev, BOTTOM_ALIGNMENT);

        botonSend.setText("-SEND-");
        botonSend.setVisible(true);
        botonSend.addActionListener((ActionEvent e) -> {
            //your actions
            mw.dispose();
            preguntas.get(i).setAnswered(true);
            runComponents(true);
        });
        panelBotones.add(botonSend, BOTTOM_ALIGNMENT);

        botonNext.setText("-->");
        botonNext.setVisible(true);
        botonNext.addActionListener((ActionEvent e) -> {
            //your actions
            mw.dispose();
            runComponents(true);
        });
        panelBotones.add(botonNext, BOTTOM_ALIGNMENT);

    }

    public static String convertToMultiline(String orig) {
        return "<html>" + orig.replaceAll("\n", "<br>");
    }

    public static void setRadioButtons(int i, JPanel panelRespuestas) {
        JRadioButton prueba1;
        JRadioButton prueba2;
        JRadioButton prueba3;
        JRadioButton prueba4;
        JRadioButton prueba5;
        JRadioButton prueba6;
        switch (preguntas.get(i).getAnswers().size()) {
            case 6:
                prueba1 = new JRadioButton(preguntas.get(i).getAnswers().get(0));
                prueba2 = new JRadioButton(preguntas.get(i).getAnswers().get(1));
                prueba3 = new JRadioButton(preguntas.get(i).getAnswers().get(2));
                prueba4 = new JRadioButton(preguntas.get(i).getAnswers().get(3));
                prueba5 = new JRadioButton(preguntas.get(i).getAnswers().get(4));
                prueba6 = new JRadioButton(preguntas.get(i).getAnswers().get(5));
                panelRespuestas.add(prueba1);
                panelRespuestas.add(prueba2);
                panelRespuestas.add(prueba3);
                panelRespuestas.add(prueba4);
                panelRespuestas.add(prueba5);
                panelRespuestas.add(prueba6);
                break;
            case 5:
                prueba1 = new JRadioButton(preguntas.get(i).getAnswers().get(0));
                prueba2 = new JRadioButton(preguntas.get(i).getAnswers().get(1));
                prueba3 = new JRadioButton(preguntas.get(i).getAnswers().get(2));
                prueba4 = new JRadioButton(preguntas.get(i).getAnswers().get(3));
                prueba5 = new JRadioButton(preguntas.get(i).getAnswers().get(4));
                panelRespuestas.add(prueba1);
                panelRespuestas.add(prueba2);
                panelRespuestas.add(prueba3);
                panelRespuestas.add(prueba4);
                panelRespuestas.add(prueba5);
                break;

            case 4:
                prueba1 = new JRadioButton(preguntas.get(i).getAnswers().get(0));
                prueba2 = new JRadioButton(preguntas.get(i).getAnswers().get(1));
                prueba3 = new JRadioButton(preguntas.get(i).getAnswers().get(2));
                prueba4 = new JRadioButton(preguntas.get(i).getAnswers().get(3));
                panelRespuestas.add(prueba1);
                panelRespuestas.add(prueba2);
                panelRespuestas.add(prueba3);
                panelRespuestas.add(prueba4);
                break;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
